### ISSUE TITLE
Issue accessing https://atlassian.github.io/data-center-helm-charts/

### ISSUE THREAD

**Issue by rhaskins** [atlassian-labs/data-center-terraform#310]
I am getting an error when accessing https://atlassian.github.io/data-center-helm-charts/ from my terraform play. I get "This site can’t provide a secure connectionatlassian.github.io sent an invalid response.
ERR_SSL_PROTOCOL_ERROR" when trying to get to that URL from a normal or incognito chrome browser.

What am I doing wrong?

**Comment by bianchi2** [comment]
@rhaskins looks like GitHub issue since it's GitHub pages. We'll raise a ticket with them.

**Comment by nanux** [comment]
@rhaskins unfortunately this is a GitHub issue and we are waiting for a response from the support team.

Thank you for raising this.

**Comment by rhaskins** [comment]
Suggestion: mirror this project somewhere else with more reliable service.

**Comment by rhaskins** [comment]
OK, I can again access the page. Thank you for your help!
